name: Build
on:
  workflow_dispatch: # Allows manual trigger
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Compile Jar File
        run: mvn clean package -Dmaven.test.skip=true -Denforcer.skip=true -Dspotless.check.skip=true
      - name: Upload Finished Jar
        uses: actions/upload-artifact@v4
        with:
          name: CoreProtect-Jar
          path: target/CoreProtect-*.jar
